### PR TITLE
[#32] Implement support for parsing decimal values

### PR DESCRIPTION
**Pull request by cleac**
Implemented a parsing of decimal values with type specification `F`

### CODE REVIEW

**Comment by cleac** [comment]
It seems that it won't be merged. Close this

**Comment by tomviner** [comment]
Pity

**Comment by r1chardj0n3s** [comment]
Please stop trying to guilt me into something here. I'm the sole maintainer of this project, and I have no spare time to spend on it.

**Comment by cleac** [comment]
Sorry, I really wasn't meaning to blame you. Project is great, yet I feel sad about this PR

**Comment by r1chardj0n3s** [comment]
Decimal (using "F") was added to parse() in version 1.8.4, released 27 May 2018. My apologies for not updating this PR.

**Pull request closed without merging**
