### PR TITLE
Add LICENSE to the manifest for PyPI

### PR DESCRIPTION
**Pull request by kyluca**
I believe this change should help to close r1chardj0n3s#82

### CODE REVIEW

**Comment by r1chardj0n3s** [comment]
Thanks!

**Comment by kyluca** [comment]
Hey @r1chardj0n3s, was this accidentally closed instead of merged?

**Comment by kyluca** [comment]
Hey @r1chardj0n3s, sorry to bother again you but I don't seem to have the permissions to "Reopen pull request". If that's possible for you to do, I think it would be cleaner than me opening a new PR :)

**Comment by r1chardj0n3s** [comment]
Sorry!

**Comment by kyluca** [comment]
No worries, cheers! :smile:

**Pull request merged**
